# Generated by Django 3.2.9 on 2021-12-23 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_customuser_useraddress_usercontact_userdetail_userkyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='test',
        ),
    ]
