FROM node:18.13-alpine as builder
WORKDIR /home/frontend
COPY . .

RUN npm install

RUN npm run build

FROM node:18.13-alpine as runner

WORKDIR /home/frontend
COPY --from=builder /home/frontend/package*.json ./
COPY --from=builder /home/frontend/build ./build

RUN npm install -g serve

EXPOSE 3000

# CMD [ "serve", "-s", "build" ]
