# Generated by Django 3.2.9 on 2021-12-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('category', models.CharField(
                    choices=[('Vegetable', 'Vegetable'), ('Medicine', 'Medicine'), ('Doctor', 'Doctor'),
                             ('Tests', 'Tests'), ('Grocery', 'Grocery'), ('Food', 'Food'), ('Snacks', 'Snacks'),
                             ('Diary', 'Diary'), ('Fuel', 'Fuel'), ('Mobile', 'Mobile'), ('Gas', 'Gas'),
                             ('Electricity', 'Electricity'), ('Water', 'Water'), ('Television', 'Television'),
                             ('Investment', 'Investment'), ('Gym', 'Gym'), ('Dietitian', 'Dietitian'),
                             ('Parking', 'Parking'), ('Gardening', 'Gardening'), ('Laundry', 'Laundry'),
                             ('Maid', 'Maid'), ('Cook', 'Cook'), ('Travel', 'Travel'), ('Transfer', 'Transfer'),
                             ('Clothes', 'Clothes'), ('Miscellaneous', 'Miscellaneous')], max_length=20, null=True)),
                ('mode', models.CharField(
                    choices=[('Cash', 'Cash'), ('Debit', 'Debit'), ('Credit', 'Credit'), ('Net Banking', 'Net Banking'),
                             ('GPay', 'GPay'), ('Paytm', 'Paytm')], max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('details', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('day', models.PositiveSmallIntegerField(editable=False, null=True)),
                ('month', models.PositiveSmallIntegerField(editable=False, null=True)),
                ('year', models.PositiveSmallIntegerField(editable=False, null=True)),
            ],
            options={
                'ordering': ['-date', '-created'],
            },
        ),
    ]
