# Generated by Django 4.2.3 on 2023-11-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Commute', 'Commute'), ('Cook', 'Cook'), ('Diary', 'Diary'), ('Doctor', 'Doctor'), ('Electricity', 'Electricity'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Gas', 'Gas'), ('Gardening', 'Gardening'), ('Grocery', 'Grocery'), ('Gym', 'Gym'), ('Internet', 'Internet'), ('Investment', 'Investment'), ('Laundry', 'Laundry'), ('Maid', 'Maid'), ('Medicine', 'Medicine'), ('Miscellaneous', 'Miscellaneous'), ('Mobile', 'Mobile'), ('OTT', 'OTT'), ('Parking', 'Parking'), ('Snacks', 'Snacks'), ('Television', 'Television'), ('Tests', 'Tests'), ('Transfer', 'Transfer'), ('Vegetable', 'Vegetable'), ('Water', 'Water')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Credit', 'Credit'), ('Debit', 'Debit'), ('GPay', 'GPay'), ('Paytm', 'Paytm'), ('Net Banking', 'Net Banking'), ('Auto Debit', 'Auto Debit')], max_length=20, null=True),
        ),
    ]
