# Generated by Django 3.2.9 on 2021-12-23 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_remove_customuser_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkyc',
            old_name='aadhaar',
            new_name='aadhar',
        ),
    ]
